### ISSUE TITLE
Data export function causing FIJI/Tissue Analyzer to freeze?

### ISSUE THREAD

**Issue by natclarke** [baigouy/tissue_analyzer#2]
Hi, I'm a running into an issue when trying to export data from TA using the 'Export cell data' function on the 'Plots' tab. After I make selections of the data to be output in the first pop-up window 'select and re-order columns', nothing happens and TA / ImageJ freezes (i.e., I get the pinwheel of death and 'application not responding', on Mac OS). 

My dataset is relatively small (~200-300 cells, 100 time points), so I don't think it is a memory issue, so I'm wondering if something else could be the source of the problem. 

Also, I'm new to using TA, so it's totally possible that I missed a necessary step that has to happen before exporting data. Before trying to export, I segmented cells, did the correction and post-processing, and ran the cell tracking algorithm. Is there anything else that needs to be done before data can be exported? 

Last, for reference, my FIJI installation is up-to-date, and I am working with Mac OS 13 with the M1 apple silicon processor. 

Thank you!

**Comment by baigouy** [comment]
Dear Nat,

I am not sure what the problem is. If you want to be sure the database is up to date and includes clones, ... then you need to go to the 'SQLite DB' tab then press the 'Generate/Update database' button (I would always recommend to do that before doing any measurment/table export). If that does not work, the SQLite DB library I use doesn't like spaces in names such as '/home/bla bla/path to my file.tif', so moving and renameing the file as follows  '/home/bla_bla/path_to_my_file.tif' should fix the issue. Also this library does not like network drives for some reason, so I would recommend to copy all files and folders locally. Please let me know if this doesn't fix the issue, in such case if I could get a sample image along with the TA output folder may help me fix the issue.

all the best,

Benoit

PS: maybe another alternative is to use the python version of TA (but the two tools are only partially compatible so this may not be a good idea for you as you are already using the java version)

**Comment by natclarke** [comment]
Hi Benoit, 

thanks for getting back to me with these suggestions. I double-checked all of my file paths to make sure there are no spaces, and this is a local folder on my computer, so those 2 factors aren't causing the issue.

I'm not certain, but I may have figured out when/where my issue is occurring. When I click the 'Generate/Update database' button, is a new file supposed to be generated? And what format should it be? For me, after I click through the settings pop-up, the process completes without any errors, but when I look in the folder containing the images there isn't a new file. There are .db files in the sub-folders for each image in the series (the ones that contain the hand correction, etc.), but beyond that, I don't see a database file. Could there be an issue at this step, as the database is (or isn't...) being generated?

If that's not the issue, or if it doesn't seem straightforward to figure out, I'm happy to try the python version. 

Thanks again,

~nat

**Comment by baigouy** [comment]
Hi Nat,

No it should not generate a new file but append tables to the existsting SQLite database TA.db. Clearly I have no idea, the only last thing that comes to my ming is that there was a problem with the SQL driver (it happened to me but very rarely), maybe a restart of the computer can fix that. If that does not work I would need a file to try by myself I guess.

hope this helps,

all the best,

Benoit

**Comment by natclarke** [comment]
Restarting my computer did the trick. I have no idea what my issue was in the end, but after restarting the export function worked just fine. Thanks again for your help!

**Comment by baigouy** [comment]
Glad we could fix it. Somehow the SQL library must have crashed for unknown reason; it is a rather picky lib with path names; it doesn't like spaces accents, special chars, network drives, ... and when it crashes once any further request will fail. However, in my hands this kind of bug happened only rarely.
